service: budgeter-api
app: budgeter-api
org: cedomirspalevic
frameworkVersion: '2.1'

provider:
  name: aws
  runtime: nodejs12.x

  environment:
    JWT_KEY: ${env:JWT_KEY}
    AWS_PLATFORM_APPLICATION_IOS: ${env:AWS_PLATFORM_APPLICATION_IOS}
    AWS_PLATFORM_APPLICATION_ANDROID: ${env:AWS_PLATFORM_APPLICATION_ANDROID}
    AWS_SNS_TOPIC: ${env:AWS_SNS_TOPIC}
    MONGO_CONNECTION_STRING: ${env:MONGO_CONNECTION_STRING}

# For serverless-bundle to remove dead code
package:
  individually: true

functions:
  auth-login:
    handler: src/lambda/auth/login/index.handler
    events:
      - http:
          path: auth/login
          method: post
  auth-verify:
    handler: src/lambda/auth/verify/index.handler
    events:
      - http:
          path: auth/verify
          method: post
  auth-register:
    handler: src/lambda/auth/register/index.handler
    events:
      - http:
          path: auth/register
          method: post
  auth-challenge:
    handler: src/lambda/auth/challenge/index.handler
    events:
      - http:
          path: auth/challenge
          method: post
  auth-challenge-confirmation:
    handler: src/lambda/auth/challengeConfirmation/index.handler
    events:
      - http:
          path: auth/challenge/{key}
          method: post
          request:
            parameters:
              paths:
                key: true

plugins:
  - '@serverless/safeguards-plugin'
  - 'serverless-bundle'
  - 'serverless-offline'
  - 'serverless-dotenv-plugin'

# Custom variables read from serverless-bundle
custom:
  serverless-offline:
    httpPort: 4000
    useChildProcesses: true
  bundle:
    sourcemaps: false
    linting: false