type User {
   id: ObjectID!
   email: String
   phoneNumber: String
   createdOn: DateTime!
   modifiedOn: DateTime!
   devices: [Device]
   preferences: Preferences
}

input UserInput {
   devices: [DeviceInput]
   preferences: PreferencesInput
}

type UserMutationResponse implements MutationResponse {
   code: String!
   success: Boolean!
   message: String!
   user: User
}
