"""
Describes a user budget for a given month
"""
type Budget {
   incomes: [BudgetIncome]
   month: Int!
   payments: [BudgetPayment]
   year: Int!
}

"""
Describes an income that is stored in a budget
"""
type BudgetIncome {
   dueToday: Boolean!
   income: Income
   numberOfOccurrences: Int!
   totalAmount: Float!
}

"""
Describes a payment that is stored in a budget
"""
type BudgetPayment {
   dueToday: Boolean!
   numberOfOccurrences: Int!
   payment: Payment
   totalAmount: Float!
}
