"""
Describes an income that a user receives
"""
type Income {
   amount: Float!
   createdOn: DateTime!
   id: ID!
   initialDate: Date!
   initialDay: Day!
   initialMonth: Month!
   initialYear: Year!
   modifiedOn: DateTime!
   recurrence: Recurrence
   title: String!
}

"""
Describes an income a user is allowed to create and update
"""
input IncomeInput {
   amount: Float!
   initialDate: Date!
   initialDay: Day!
   initialMonth: Month!
   initialYear: Year!
   recurrence: Recurrence!
   tags: [String]
   title: String!
}

"""
Describes the response type when a user is attempting to add, update, or remove an income
"""
type IncomeMutationResponse implements MutationResponse {
   income: Income
   message: String!
   success: Boolean!
}
