"""
Describes the guideline for a mutation responses
"""
interface MutationResponse {
   message: String!
   success: Boolean!
}

"""
Describes all of the mutation queries that are allowed to be executed
"""
type Mutation {
   addDevice(device: DeviceInput): DeviceMutationResponse
   addIncome(income: AddIncomeInput): IncomeMutationResponse
   addPayment(payment: AddPaymentInput): PaymentMutationResponse
   addPaymentTag(paymentTag: PaymentTagInput): PaymentTagMutationResponse
   removeDevice(device: DeviceInput): DeviceMutationResponse
   removeIncome(id: ID): IncomeMutationResponse
   removePayment(id: ID): PaymentMutationResponse
   removePaymentTag(id: ID): PaymentTagMutationResponse
   updateIncome(id: ID, income: UpdateIncomeInput): IncomeMutationResponse
   updatePayment(id: ID, payment: UpdatePaymentInput): PaymentMutationResponse
   updateUserPreferences(
      preferences: PreferencesInput
   ): UpdatePreferencesResponse
}
