"""
Describes a payment that a user makes
"""
type Payment {
   amount: Float!
   createdOn: DateTime!
   endDate: Date
   endDay: Day
   endMonth: Month
   endYear: Year
   id: ID!
   initialDate: Date!
   initialDay: Day!
   initialMonth: Month!
   initialYear: Year!
   modifiedOn: DateTime!
   recurrence: Recurrence!
   tags: [PaymentTag]
   title: String!
}

"""
Describes a payment a user is allowed to add
"""
input AddPaymentInput {
   amount: Float!
   endDate: Date
   endDay: Day
   endMonth: Month
   endYear: Year
   initialDate: Date!
   initialDay: Day!
   initialMonth: Month!
   initialYear: Year!
   recurrence: Recurrence!
   tags: [String]
   title: String!
}

"""
Describes a payment a user is allowed to update
"""
input UpdatePaymentInput {
   amount: Float
   endDate: Date
   endDay: Day
   endMonth: Month
   endYear: Year
   initialDate: Date
   initialDay: Day
   initialMonth: Month
   initialYear: Year
   recurrence: Recurrence
   tags: [String]
   title: String
}

"""
Describes the response type when a user is attempting to add, update, or remove a payment
"""
type PaymentMutationResponse implements MutationResponse {
   message: String!
   payment: Payment
   success: Boolean!
}
