"""
Describes all of the queries that can be executed
"""
type Query {
   budget(day: Day!, month: Month!, year: Year!): Budget
   incomeById(id: ID): Income
   incomes: [Income]
   paymentById(id: ID): Payment
   paymentTags: [PaymentTag]
   payments: [Payment]
   user: User
}
