"""
Describes a user stored in the system
"""
type User {
   createdOn: DateTime!
   devices: [Device]
   email: String
   id: ID!
   modifiedOn: DateTime!
   phoneNumber: String
   preferences: Preferences
}
