name: Build, Test, Prod Deploy

on:
   push:
      branches:
         - main

jobs:
   build-test-deploy:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - name: Install NPM dependencies
           run: npm ci
         - name: Configure AWS credentials
           id: creds
           uses: aws-actions/configure-aws-credentials@v1
           with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ secrets.AWS_REGION }}
         - name: Setup ENV
           run: npm run env:dev
         - name: Build code
           run: npm run build
         - name: Deploy
           uses: serverless/github-action@master
           with:
              args: deploy --stage prod
           env:
              SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
              # or if using AWS credentials directly
              # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
              # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
