name: Build, Test

on: pull_request

jobs:
   build-test:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - name: Install NPM dependencies
           run: npm ci
         - name: Setup ENV
           run: npm run env:dev
         - name: Configure AWS credentials
           id: creds
           uses: aws-actions/configure-aws-credentials@v1
           with:
              aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ env.AWS_REGION }}
         - name: Build code
           run: npm run build
